version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "13:00"
  open-pull-requests-limit: 20
  versioning-strategy: increase
  commit-message:
    prefix: "[skip netlify]"
  ignore:
    - dependency-name: ember-responsive-image
      versions:
        - "> 2.0.0"
