version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "13:00"
  open-pull-requests-limit: 20
  versioning-strategy: increase
  ignore:
  - dependency-name: ember-responsive-image
    versions:
    - "> 2.0.0, < 3"
  - dependency-name: ember-cli-babel
    versions:
    - 7.26.3
  - dependency-name: ember-template-lint
    versions:
    - 3.1.1
    - 3.2.0
  - dependency-name: ember-responsive-image
    versions:
    - 2.0.0
  commit-message:
    prefix: "[skip netlify]"
